### ISSUE TITLE
Any reason this cookbook shouldn't be able to build mesos 0.25.x?

### ISSUE THREAD

**Issue by rberger** [mdsol/mesos_cookbook#114]
Should I be able to build mesos 0.25.x (or 0.24.x) with this cookbook? Starting new project and would like to use the latest Mesos

Thanks!

**Comment by tubit** [comment]
Until today this cookbook is only compatible with mesos 0.23.0. I created a pull request for 0.23.1 (https://github.com/mdsol/mesos_cookbook/pull/113). My plan is to prepare a pull request for 0.24 and 0.25 as well.

**Comment by rberger** [comment]
Great! Any feel for timing on 0.25? Can I be of any assistance?

Robert J Berger
http://linkedin.com/in/rberger

**Comment by tubit** [comment]
I can not estimate any timings for 0.25, sorry.

**Comment by rveznaver** [comment]
Hi @rberger, if you'd like to test without waiting for an official release of the cookbook; overwrite the allowed attributes in ```default['mesos']['options']``` and set the mesos version to 0.25.0 in a node file, kitchen test, or wrapper cookbook. That should (most probably) do it.

**Comment by rberger** [comment]
Thanks @rveznaver I'll give that a try and let you know

**Comment by albsOps** [comment]
@rveznaver I can confirm that overriding the attribute allows the installation of mesos 0.25

**Comment by aktarali** [comment]
@rberger Would you please provide instructions on how you did this? I am also interested in installing 0.25 version. Kindly if possible provide step by step guide. Any help would be greatly appreciated.

The README has mention of attributes/mesos_options.rb, however, that file does not exist. Do you need to create this file and add the options for the new version? Please send me a detailed guide as soon as you can.

**Comment by rveznaver** [comment]
@aktarali The master branch has been updated recently with an unreleased feature which removes this file and allows for any mesos version to be used.

**Comment by aktarali** [comment]
@rberger I have a role defined like so:
{
  "name": "mesos_master",
  "description": "",
  "json_class": "Chef::Role",
  "default_attributes": {

  },
  "override_attributes": {
    "mesos:": {

    },
    "version:0.25.0": {

    },
    "master:": {
      "flags:": {
        "cluster:'mesos-sandbox'": {

        }
      }
    },
    "zk:'zk://127.0.0.1:2181/mesos'": {

    }
  },
  "chef_type": "role",
  "run_list": [
    "recipe[mesos::master]"
  ],
  "env_run_lists": {

  }
}

And getting the following errors running centos7. Any ideas? Its also installing version 0.22 instead of 0.25.

[2015-12-16T14:53:22+00:00] INFO: service[mesos-slave-default] disabled

    - disable service service[mesos-slave-default]
Recipe: mesos::master
  * ruby_block[mesos-master-configuration-validation] action run[2015-12-16T14:53:22+00:00] INFO: Processing ruby_block[mesos-master-configuration-validation] action run (mesos::master line 27)

    
    ================================================================================
    Error executing action `run` on resource 'ruby_block[mesos-master-configuration-validation]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /usr/sbin/mesos-master --help ----
    Ran /usr/sbin/mesos-master --help returned 1
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/mesos/recipes/master.rb:32:in `block (2 levels) in from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/mesos/recipes/master.rb
    
     27: ruby_block 'mesos-master-configuration-validation' do
     28:   block do
     29:     # Get Mesos --help
     30:     help = Mixlib::ShellOut.new("#{node['mesos']['master']['bin']} --help")
     31:     help.run_command
     32:     help.error!
     33:     # Extract options
     34:     options = help.stdout.strip.scan(/^  --(?:\[no-\])?(\w+)/).flatten - ['help']
     35:     # Check flags are in the list
     36:     node['mesos']['master']['flags'].keys.each do |flag|
     37:       unless options.include?(flag)
     38:         Chef::Application.fatal!("Invalid Mesos configuration option: #{flag}. Aborting!", 1000)
     39:       end
     40:     end
     41:   end
     42: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/mesos/recipes/master.rb:27:in `from_file'
    
    ruby_block("mesos-master-configuration-validation") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      block_name "mesos-master-configuration-validation"
      declared_type :ruby_block
      cookbook_name "mesos"
      recipe_name "master"
      block #<Proc:0x000000076a6c18@/var/chef/cache/cookbooks/mesos/recipes/master.rb:28>
    end
    
[2015-12-16T14:53:23+00:00] INFO: Running queued delayed notifications before re-raising exception
[2015-12-16T14:53:23+00:00] INFO: [template[mesos-master-init]] sending run action to execute[systemctl-daemon-reload] (delayed)
Recipe: mesos::install
  * execute[systemctl-daemon-reload] action run[2015-12-16T14:53:23+00:00] INFO: Processing execute[systemctl-daemon-reload] action run (mesos::install line 109)
[2015-12-16T14:53:23+00:00] INFO: execute[systemctl-daemon-reload] ran successfully

    - execute /bin/systemctl --system daemon-reload
[2015-12-16T14:53:23+00:00] INFO: [template[mesos-master-init]] sending restart action to service[mesos-master] (delayed)
Recipe: mesos::master
  * service[mesos-master] action restart[2015-12-16T14:53:23+00:00] INFO: Processing service[mesos-master] action restart (mesos::master line 69)
[2015-12-16T14:53:23+00:00] INFO: service[mesos-master] restarted

    - restart service service[mesos-master]

Running handlers:
[2015-12-16T14:53:23+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-12-16T14:53:23+00:00] ERROR: Exception handlers complete
Chef Client failed. 16 resources updated in 11 minutes 22 seconds
[2015-12-16T14:53:23+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-12-16T14:53:23+00:00] ERROR: ruby_block[mesos-master-configuration-validation] (mesos::master line 27) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/sbin/mesos-master --help ----
STDOUT: 
STDERR: Usage: mesos-master [...]

Sorry for lengthy output..can you assist? What am I doing wrong?

**Comment by rveznaver** [comment]
@aktarali The role file doesn't look quite right. In any case, #117 bumps the Mesos version to 0.25.0 if you don't mind waiting for a couple of days.

**Comment by rberger** [comment]
FYI all we did was what @rveznaver originally suggested. We updated `attributes/default.rb` and `attributes/mesos_options.rb` to add 
```
 || node['mesos']['version'] == '0.24.0' || node['mesos']['version'] == '0.25.0'
```

But its great that it will be officially supported any moment now. Probably worth waiting for that.

**Comment by rveznaver** [comment]
Hi @aktarali, @rberger, @albsOps,

The PR supporting 0.25.0 has been tested, reviewed, and merged.
I invite you to try out the master branch If you feel adventurous :)

**Comment by albsOps** [comment]
Awesome! I will try it soon. Thanks

**Comment by rayrod2030** [comment]
@rveznaver I can publish master to the supermarket today if you are ok with that.

**Comment by rveznaver** [comment]
@rayrod2030 Please wait until I write a proper changelog and update the readme. Thanks.

**Comment by rveznaver** [comment]
@rayrod2030 #118

**Comment by rayrod2030** [comment]
3.5.0 is now published to the supermarket.  https://supermarket.chef.io/cookbooks/mesos.  Thanks everybody for your extreme patience and we owe it all to @rveznaver for joining as co-author of this cookbook!
