### ISSUE TITLE
dynamic zk values

### ISSUE THREAD

**Issue by aktarali** [mdsol/mesos_cookbook#130]
Hi Guys;

With your help, I was able to get my mesos master cluster working perfectly with zookeeper. Dynamic on the fly zk node values provided by chef-search. Would you guys consider adding this method to cookbook as a default method? 
Its thoroughly tested on my end and works perfectly every time.

Wrapper cookbook:
attributes:
zks = "zk://#{Chef::Search::Query.new.search(:node, 'recipes:zookeeper\:\:default').first.map { |zk| "#{zk['fqdn']}:#{zk['zookeeper']['config']['clientPort']}" }.sort.join(',')}/#{node['mesos']['zookeeper_path'] }"
default['mesos']['master']['flags']['zk']    = zks
default['mesos']['slave']['flags']['master'] = zks

Recipe:
mesos_master.rb
include_recipe 'mesos::master'

This allows for the following mesos process to look like this:
    --master='zk://ip-172-31-35-170.eu-west-1.compute.internal:2181,ip-172-31-37-167.eu-west-1.compute.internal:2181,ip-172-31-44-83.eu-west-1.compute.internal:2181/mesos' \

Thanks
Ali.

**Comment by rveznaver** [comment]
Hi @aktarali,

I would prefer not to include this method due to the fact that if it were included, we would have to depend on the ZooKeeper cookbook, a service that Mesos itself depends on only in HA configurations, and even that is slowly evolving towards supporting multiple leader election backends (most notably Consul and etcd). So, we could mention it in the README if you wish (you could make a pull request for that), but setting it as default would create a hard dependency on another cookbook (something which I would like to avoid since it makes testing and maintenance more difficult).

**Comment by aktarali** [comment]
That's fair though. I would other to use consul anyway once it becomes
supported.

Any ideas when this might happen?

**Comment by rveznaver** [comment]
Depends on https://issues.apache.org/jira/browse/MESOS-3797.
