### ISSUE TITLE
Is the /etc/hostname operation necessary?

### ISSUE THREAD

**Issue by luntzel** [mdsol/mesos_cookbook#42]
How necesary is the following block from https://github.com/mdsol/mesos_cookbook/blob/develop/recipes/master.rb

I prefer to keep control of hostnames with the hostnames cookbook. 

```
# If we are on ec2 set the public dns as the hostname so that
# mesos master redirection works properly.
if node.attribute?('ec2') && node['mesos']['set_ec2_hostname']
  bash 'set-aws-public-hostname' do
    user 'root'
    code <<-EOH
      PUBLIC_DNS=`wget -q -O - http://instance-data.ec2.internal/latest/meta-data/public-hostname`
      hostname $PUBLIC_DNS
      echo $PUBLIC_DNS > /etc/hostname
      HOSTNAME=$PUBLIC_DNS  # Fix the bash built-in hostname variable too
    EOH
    not_if 'hostname | grep amazonaws.com'
  end
end
```

**Comment by ankurcha** [comment]
Adding my 2 cents: We need some sort of better implementation. In case of a deployment in vpc you may not have a public-hostname. I would suggest we let the user set the hostname on their own and the best we can do is allow them to set/reset properties using `--hostname`. Essentially, the `set_ec2_hostname` defaulting to true may not be the correct behaviour in ec2 (also, now that vpc is the default/recommended deployment strategy).

**Comment by rayrod2030** [comment]
@luntzel @ankurcha Valid points on this and I'll be submitting a patch so that the default behavior is to not change machine hostnames for any environment and instead rely on the --hostname flag for proper mesos-master leader redirection.  I wrote this bit of code for a while ago for Mesos 0.13.0 before the --hostname flag existed so it doesn't make sense anymore and is way too opinionated and approach.  Thanks for the feedback on this!

**Comment by rayrod2030** [comment]
PR https://github.com/mdsol/mesos_cookbook/pull/63 removes this functionality.

**Comment by rayrod2030** [comment]
Closing this issue as this functionality is no longer present in the cookbook.  Thanks for the feedback @ankurcha and @luntzel.
